{{- /*
Copyright 2026 GoodRx, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/}}

{{- if .Values.secrets.postgres.enabled }}
{{- $namespace := .Release.Namespace -}}
{{- $secretName := "" -}}
{{- if .Values.secrets.postgres.fullnameOverride -}}
  {{- $secretName = .Values.secrets.postgres.fullnameOverride -}}
{{- else -}}
  {{- $secretName = include "lifecycle-keycloak.postgresSecretName" . -}}
{{- end -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  namespace: {{ $namespace }}
  labels:
    {{- include "lifecycle-keycloak.labels" (merge (dict "component" "postgres") $) | nindent 4 }}
  {{- with .Values.secrets.postgres.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  POSTGRES_USERNAME: {{ include "lifecycle-keycloak.getValueFromSecret" (list $secretName "POSTGRES_USERNAME" .Values.keycloakPostgres.auth.username "keycloak" $namespace) | quote }}
  POSTGRES_ADMIN_PASSWORD: {{ include "lifecycle-keycloak.getValueFromSecret" (list $secretName "POSTGRES_ADMIN_PASSWORD" .Values.secrets.postgres.adminPassword (randAlphaNum 40) $namespace) | quote }}
  POSTGRES_USER_PASSWORD: {{ include "lifecycle-keycloak.getValueFromSecret" (list $secretName "POSTGRES_USER_PASSWORD" .Values.secrets.postgres.userPassword (randAlphaNum 40) $namespace) | quote }}
{{- end }}
